# Generated by Django 4.1 on 2022-09-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywatchlistitem',
            old_name='movie_reviw',
            new_name='movie_review',
        ),
    ]
